# Generated by Django 3.1 on 2020-08-26 05:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Nome')),
                ('birthdate', models.DateField(default=datetime.date.today, verbose_name='Data de Nascimento')),
                ('admission_date', models.DateField(default=datetime.date.today, verbose_name='Data de Admissão')),
                ('job_role', models.CharField(max_length=255, verbose_name='Cargo de Trabalho')),
                ('projects', models.ManyToManyField(related_name='navers', to='projects.Project', verbose_name='Projeto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navers', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Naver',
                'verbose_name_plural': 'Navers',
            },
        ),
    ]
