# Generated by Django 3.1 on 2020-08-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naver',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Naver', 'verbose_name_plural': 'Navers'},
        ),
    ]
